package types

import "time"

type Ticket struct {
	Id                         int             `json:"id,omitempty"`
	Summary                    string          `json:"summary"`
	RecordType                 string          `json:"recordType,omitempty"`
	Board                      Board           `json:"board,omitempty"`
	Status                     ServiceStatus   `json:"status,omitempty"`
	WorkRole                   WorkRole        `json:"workRole,omitempty"`
	WorkType                   WorkType        `json:"workType,omitempty"`
	Company                    Company         `json:"company"`
	Site                       Site            `json:"site,omitempty"`
	SiteName                   string          `json:"siteName,omitempty"`
	AddressLine1               string          `json:"addressLine1,omitempty"`
	AddressLine2               string          `json:"addressLine2,omitempty"`
	City                       string          `json:"city,omitempty"`
	StateIdentifier            string          `json:"stateIdentifier,omitempty"`
	Zip                        string          `json:"zip,omitempty"`
	Country                    Country         `json:"country,omitempty"`
	Contact                    Contact         `json:"contact,omitempty"`
	ContactName                string          `json:"contactName,omitempty"`
	ContactPhoneNumber         string          `json:"contactPhoneNumber,omitempty"`
	ContactPhoneExtension      string          `json:"contactPhoneExtension,omitempty"`
	ContactEmailAddress        string          `json:"contactEmailAddress,omitempty"`
	Type                       ServiceType     `json:"type,omitempty"`
	SubType                    ServiceSubType  `json:"subType,omitempty"`
	Item                       ServiceItem     `json:"item,omitempty"`
	Team                       ServiceTeam     `json:"team,omitempty"`
	Owner                      Member          `json:"owner,omitempty"`
	Priority                   Priority        `json:"priority,omitempty"`
	ServiceLocation            ServiceLocation `json:"serviceLocation,omitempty"`
	Source                     ServiceSource   `json:"source,omitempty"`
	RequiredDate               time.Time       `json:"requiredDate,omitempty"`
	BudgetHours                int             `json:"budgetHours,omitempty"`
	Opportunity                Opportunity     `json:"opportunity,omitempty"`
	Agreement                  Agreement       `json:"agreement,omitempty"`
	AgreementType              string          `json:"agreementType,omitempty"`
	Severity                   string          `json:"severity,omitempty"`
	Impact                     string          `json:"impact,omitempty"`
	ExternalXRef               string          `json:"externalXRef,omitempty"`
	PoNumber                   string          `json:"poNumber,omitempty"`
	KnowledgeBaseCategoryId    int             `json:"knowledgeBaseCategoryId,omitempty"`
	KnowledgeBaseSubCategoryId int             `json:"knowledgeBaseSubCategoryId,omitempty"`
	AllowAllClientsPortalView  bool            `json:"allowAllClientsPortalView,omitempty"`
	CustomerUpdatedFlag        bool            `json:"customerUpdatedFlag,omitempty"`
	AutomaticEmailContactFlag  bool            `json:"automaticEmailContactFlag,omitempty"`
	AutomaticEmailResourceFlag bool            `json:"automaticEmailResourceFlag,omitempty"`
	AutomaticEmailCcFlag       bool            `json:"automaticEmailCcFlag,omitempty"`
	AutomaticEmailCc           string          `json:"automaticEmailCc,omitempty"`
	InitialDescription         string          `json:"initialDescription,omitempty"`
	InitialInternalAnalysis    string          `json:"initialInternalAnalysis,omitempty"`
	InitialResolution          string          `json:"initialResolution,omitempty"`
	InitialDescriptionFrom     string          `json:"initialDescriptionFrom,omitempty"`
	ContactEmailLookup         string          `json:"contactEmailLookup,omitempty"`
	ProcessNotifications       bool            `json:"processNotifications,omitempty"`
	SkipCallback               bool            `json:"skipCallback,omitempty"`
	ClosedDate                 string          `json:"closedDate,omitempty"`
	ClosedBy                   string          `json:"closedBy,omitempty"`
	ClosedFlag                 bool            `json:"closedFlag,omitempty"`
	ActualHours                int             `json:"actualHours,omitempty"`
	Approved                   bool            `json:"approved,omitempty"`
	EstimatedExpenseCost       int             `json:"estimatedExpenseCost,omitempty"`
	EstimatedExpenseRevenue    int             `json:"estimatedExpenseRevenue,omitempty"`
	EstimatedProductCost       int             `json:"estimatedProductCost,omitempty"`
	EstimatedProductRevenue    int             `json:"estimatedProductRevenue,omitempty"`
	EstimatedTimeCost          int             `json:"estimatedTimeCost,omitempty"`
	EstimatedTimeRevenue       int             `json:"estimatedTimeRevenue,omitempty"`
	BillingMethod              string          `json:"billingMethod,omitempty"`
	BillingAmount              int             `json:"billingAmount,omitempty"`
	HourlyRate                 int             `json:"hourlyRate,omitempty"`
	SubBillingMethod           string          `json:"subBillingMethod,omitempty"`
	SubBillingAmount           int             `json:"subBillingAmount,omitempty"`
	SubDateAccepted            string          `json:"subDateAccepted,omitempty"`
	DateResolved               string          `json:"dateResolved,omitempty"`
	DateResplan                string          `json:"dateResplan,omitempty"`
	DateResponded              string          `json:"dateResponded,omitempty"`
	ResolveMinutes             int             `json:"resolveMinutes,omitempty"`
	ResPlanMinutes             int             `json:"resPlanMinutes,omitempty"`
	RespondMinutes             int             `json:"respondMinutes,omitempty"`
	IsInSla                    bool            `json:"isInSla,omitempty"`
	KnowledgeBaseLinkId        int             `json:"knowledgeBaseLinkId,omitempty"`
	Resources                  string          `json:"resources,omitempty"`
	ParentTicketId             int             `json:"parentTicketId,omitempty"`
	HasChildTicket             bool            `json:"hasChildTicket,omitempty"`
	HasMergedChildTicketFlag   bool            `json:"hasMergedChildTicketFlag,omitempty"`
	KnowledgeBaseLinkType      string          `json:"knowledgeBaseLinkType,omitempty"`
	BillTime                   string          `json:"billTime,omitempty"`
	BillExpenses               string          `json:"billExpenses,omitempty"`
	BillProducts               string          `json:"billProducts,omitempty"`
	PredecessorType            string          `json:"predecessorType,omitempty"`
	PredecessorId              int             `json:"predecessorId,omitempty"`
	PredecessorClosedFlag      bool            `json:"predecessorClosedFlag,omitempty"`
	LagDays                    int             `json:"lagDays,omitempty"`
	LagNonworkingDaysFlag      bool            `json:"lagNonworkingDaysFlag,omitempty"`
	EstimatedStartDate         time.Time       `json:"estimatedStartDate,omitempty"`
	Duration                   int             `json:"duration,omitempty"`
	Location                   SystemLocation  `json:"location,omitempty"`
	Department                 Department      `json:"department,omitempty"`
	MobileGuid                 string          `json:"mobileGuid,omitempty"`
	Sla                        Sla             `json:"sla,omitempty"`
	SlaStatus                  string          `json:"slaStatus,omitempty"`
	RequestForChangeFlag       bool            `json:"requestForChangeFlag,omitempty"`
	Currency                   Currency        `json:"currency,omitempty"`
	MergedParentTicket         *Ticket         `json:"mergedParentTicket,omitempty"`
	IntegratorTags             []string        `json:"integratorTags,omitempty"`
	Info                       Info            `json:"_info,omitempty"`
	EscalationStartDateUTC     string          `json:"escalationStartDateUTC,omitempty"`
	EscalationLevel            int             `json:"escalationLevel,omitempty"`
	MinutesBeforeWaiting       int             `json:"minutesBeforeWaiting,omitempty"`
	RespondedSkippedMinutes    int             `json:"respondedSkippedMinutes,omitempty"`
	ResplanSkippedMinutes      int             `json:"resplanSkippedMinutes,omitempty"`
	RespondedHours             int             `json:"respondedHours,omitempty"`
	RespondedBy                string          `json:"respondedBy,omitempty"`
	ResplanHours               int             `json:"resplanHours,omitempty"`
	ResplanBy                  string          `json:"resplanBy,omitempty"`
	ResolutionHours            int             `json:"resolutionHours,omitempty"`
	ResolvedBy                 string          `json:"resolvedBy,omitempty"`
	MinutesWaiting             int             `json:"minutesWaiting,omitempty"`
	CustomFields               []CustomField   `json:"customFields,omitempty"`
}
